# Form implementation generated from reading ui file 'interface_updated.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import psycopg2
from dbsettings import database_parametres

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon("icons/ipng_logo.png"))
        MainWindow.resize(1128, 729)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.widget = QtWidgets.QWidget(parent=self.widget_3)
        self.widget.setGeometry(QtCore.QRect(10, 10, 961, 42))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("background-color: #f5eded;")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu_button = QtWidgets.QPushButton(parent=self.widget)
        self.menu_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/588a6507d06f6719692a2d15.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_button.setIcon(icon)
        self.menu_button.setIconSize(QtCore.QSize(25, 25))
        self.menu_button.setCheckable(True)
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_3.addWidget(self.menu_button)
        spacerItem = QtWidgets.QSpacerItem(884, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.user_button = QtWidgets.QPushButton(parent=self.widget)
        self.user_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/2343640.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user_button.setIcon(icon1)
        self.user_button.setIconSize(QtCore.QSize(25, 25))
        self.user_button.setObjectName("user_button")
        self.horizontalLayout_3.addWidget(self.user_button)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 971, 641))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 951, 611))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(100)
        self.tableWidget.setRowCount(100)
        column_names_search = ["item_id","author_name","linkurl","genre","type","journal_title","publisher","title_article"]
        self.tableWidget.setHorizontalHeaderLabels(column_names_search)
        self.textEdit = QtWidgets.QTextEdit(parent=self.page)
        self.textEdit.setGeometry(QtCore.QRect(90, 0, 191, 31))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border: 1px solid #ced4da;\n"
"    font-size: 10pt;\n"
"        color: gray;\n"
"        font-weight: bold;\n"
"    border-radius:16px;\n"
"}\n"
"\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(parent=self.page)
        self.comboBox.setGeometry(QtCore.QRect(10, 0, 71, 31))
        self.comboBox.setStyleSheet("#comboBox{\n"
"    border: 1px solid #ced4da;\n"
"    border-radius:4px;\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"#comboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"#comboBox::down-arrow {\n"
"    image: url(icons/arrow-204-32.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right:15px;\n"
"}\n"
"\n"
"#comboBox:on {\n"
"     border: 4px solid #c2dbfe;\n"
" }\n"
"\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    padding:5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;  /*去虚线*/\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    background-color:#FFFFFF;\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Primary = QtWidgets.QPushButton(parent=self.page)
        self.Primary.setGeometry(QtCore.QRect(300, 0, 161, 31))
        self.Primary.setStyleSheet("QPushButton {\n"
"    font-size: 12pt;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#Primary {\n"
"\n"
"    background-color:#eedd66;\n"
"}\n"
"\n"
"#Primary:hover {\n"
"    background-color: #9e986d;\n"
"}\n"
"\n"
"#Primary:pressed {\n"
"    border: 4px solid #98c1fe;\n"
"}")
        self.Primary.setObjectName("Primary")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_article = QtWidgets.QTableWidget(parent=self.page_2)
        self.tableWidget_article.setGeometry(QtCore.QRect(0, 0, 971, 631))
        self.tableWidget_article.setObjectName("tableWidget_article")
        self.tableWidget_article.setColumnCount(100)
        self.tableWidget_article.setRowCount(100)
        column_names_article = ["item_id", "linkurl", "genre", "type", "journal_title", "issn","eissn","publisher",
                                "vak",
                                "rcsi", "wos", "scopus", "quartile", "year", "number", "contnumber", "volume",
                                "page_begin",
                                "page_end", "language", "title_article", "doi", "edn", "grnti", "risc", "corerisc"]
        self.tableWidget_article.setHorizontalHeaderLabels(column_names_article)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableWidget_article_author = QtWidgets.QTableWidget(parent=self.page_3)
        self.tableWidget_article_author.setGeometry(QtCore.QRect(0, 0, 971, 621))
        self.tableWidget_article_author.setObjectName("tableWidget_article_author")
        self.tableWidget_article_author.setColumnCount(100)
        self.tableWidget_article_author.setRowCount(100)
        column_names_article_author = ["item_id", "author_id", "author_name"]
        self.tableWidget_article_author.setHorizontalHeaderLabels(column_names_article_author)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tableWidget_authors = QtWidgets.QTableWidget(parent=self.page_4)
        self.tableWidget_authors.setGeometry(QtCore.QRect(0, 0, 971, 631))
        self.tableWidget_authors.setObjectName("tableWidget_authors")
        self.tableWidget_authors.setColumnCount(100)
        self.tableWidget_authors.setRowCount(100)
        column_names_authors = ["author_id", "lastname", "initials"]
        self.tableWidget_authors.setHorizontalHeaderLabels(column_names_authors)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.tableWidget_authors_organisations = QtWidgets.QTableWidget(parent=self.page_5)
        self.tableWidget_authors_organisations.setGeometry(QtCore.QRect(0, 0, 971, 631))
        self.tableWidget_authors_organisations.setObjectName("tableWidget_authors_organisations")
        self.tableWidget_authors_organisations.setColumnCount(100)
        self.tableWidget_authors_organisations.setRowCount(100)
        column_names_authors_organisations = ["author_id", "author_name", "org_id", "org_name"]
        self.tableWidget_authors_organisations.setHorizontalHeaderLabels(column_names_authors_organisations)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.tableWidget_organisations = QtWidgets.QTableWidget(parent=self.page_6)
        self.tableWidget_organisations.setGeometry(QtCore.QRect(0, 0, 971, 631))
        self.tableWidget_organisations.setObjectName("tableWidget_organisations")
        self.tableWidget_organisations.setColumnCount(100)
        self.tableWidget_organisations.setRowCount(100)
        column_names_organisations = ["org_id", "org_name"]
        self.tableWidget_organisations.setHorizontalHeaderLabels(column_names_organisations)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.tableWidget_add_row = QtWidgets.QTableWidget(parent=self.page_7)
        self.tableWidget_add_row.setGeometry(QtCore.QRect(30, 40, 911, 71))
        self.tableWidget_add_row.setRowCount(1)
        self.tableWidget_add_row.setColumnCount(39)
        self.tableWidget_add_row.setObjectName("tableWidget_add_row")
        column_names_add = ["item_id", "linkurl", "genre", "type", "journal_title", "issn", "eissn",
                        "publisher", "vak", "rcsi", "wos", "scopus", "quartile", "year", "number",
                        "contnumber", "volume", "page_begin", "page_end", "language",
                        "title_article", "doi", "edn", "grnti", "risc", "corerisc","author_id",
                        "last_name", "first_name", "patronymic","lastname_with_initials", "position", "degree", "employment_relationship",
                        "birth_year", "author_count", "aff_count", "org_id", "org_name"]
        self.tableWidget_add_row.setHorizontalHeaderLabels(column_names_add)
        self.add_one_row_button = QtWidgets.QPushButton(parent=self.page_7)
        self.add_one_row_button.setGeometry(QtCore.QRect(250, 260, 491, 191))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icone-excel-jaune.png"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        iconDB = QtGui.QIcon()
        iconDB.addPixmap(QtGui.QPixmap("icons/db_icon_orange-removebg-preview.png"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_one_row_button.setIcon(iconDB)
        self.add_one_row_button.setIconSize(QtCore.QSize(90, 90))
        self.add_one_row_button.setObjectName("add_one_row_button")
        self.stackedWidget.addWidget(self.page_7)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.widget_2 = QtWidgets.QWidget(parent=self.page_9)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 971, 651))
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(230, 160, 491, 191))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icone-excel-jaune.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(90, 90))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.tableWidget_for_selecting_columns = QtWidgets.QTableWidget(parent=self.page_10)
        self.tableWidget_for_selecting_columns.setGeometry(QtCore.QRect(20, 60, 911, 71))
        self.tableWidget_for_selecting_columns.setRowCount(1)
        self.tableWidget_for_selecting_columns.setColumnCount(38)
        self.comboboxes = []

        for column in range(38):
                combobox_name = f"combobox{column + 1}"  # Generate unique combobox name

                # Create the combobox dynamically using the unique name
                setattr(self, combobox_name, QtWidgets.QComboBox())

                data = [
                        "None", "item_id", "linkurl", "genre", "type", "journal_title", "issn", "eissn",
                        "publisher", "vak", "rcsi", "wos", "scopus", "quartile", "year", "number",
                        "contnumber", "volume", "page_begin", "page_end", "language",
                        "title_article", "doi", "edn", "grnti", "risc", "corerisc",
                        "last_name", "first_name", "patronymic", "position", "degree", "employment_relationship",
                        "birth_year", "author_count", "aff_count", "org_id", "org_name"
                ]

                # Access the dynamically created combobox using the unique name
                combobox = getattr(self, combobox_name)

                combobox.clear()  # Clear any existing items
                combobox.addItems(data)
                self.tableWidget_for_selecting_columns.setCellWidget(0, column, combobox)

                self.comboboxes.append(combobox)


        self.tableWidget_for_selecting_columns.setObjectName("tableWidget_for_selecting_columns")
        self.general_data_export_button = QtWidgets.QPushButton(parent=self.page_10)
        self.general_data_export_button.setGeometry(QtCore.QRect(230, 250, 491, 191))
        self.general_data_export_button.setIcon(icon2)
        self.general_data_export_button.setIconSize(QtCore.QSize(90, 90))
        self.general_data_export_button.setObjectName("general_data_export_button")
        self.stackedWidget.addWidget(self.page_10)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.progressBar = QtWidgets.QProgressBar(parent=self.page_8)
        self.progressBar.setGeometry(QtCore.QRect(80, 420, 821, 161))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("#progressBar {background-color: rgb(98, 114, 164);\n"
                                       "color:  #554348;\n"
                                       "border-style: none;\n"
                                       "border-radius: 10px;\n"
                                       "text-align: center;\n"
                                       "}\n"
                                       "#progressBar::chunk {\n"
                                       "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 128, 8, 255), stop:1 rgba(255, 200, 55, 255));\n"
                                       "    border-radius: 10px;\n"
                                       "}\n"
                                       "")
        self.progressBar.setProperty("value", 89)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(parent=self.page_8)
        self.label_4.setGeometry(QtCore.QRect(140, 90, 681, 211))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("#label_4 {\n"
                                   "color: black;\n"
                                   "font-weight: bold;\n"
                                   "font-size: 50pt;\n"
                                   "}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_8)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.widget_onlyicons = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_onlyicons.setMaximumSize(QtCore.QSize(51, 16777215))
        self.widget_onlyicons.setObjectName("widget_onlyicons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_onlyicons)
        self.verticalLayout_3.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget_onlyicons)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/ipng_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.home_button_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.home_button_iconwidget.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/free-home-icon-2502-thumb.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_button_iconwidget.setIcon(icon3)
        self.home_button_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.home_button_iconwidget.setCheckable(True)
        self.home_button_iconwidget.setAutoExclusive(True)
        self.home_button_iconwidget.setObjectName("home_button_iconwidget")
        self.verticalLayout.addWidget(self.home_button_iconwidget)
        self.articleDB_button_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.articleDB_button_iconwidget.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/database-icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.articleDB_button_iconwidget.setIcon(icon4)
        self.articleDB_button_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.articleDB_button_iconwidget.setCheckable(True)
        self.articleDB_button_iconwidget.setAutoExclusive(True)
        self.articleDB_button_iconwidget.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_article, 'SELECT * FROM article'))
        self.articleDB_button_iconwidget.setObjectName("articleDB_button_iconwidget")
        self.verticalLayout.addWidget(self.articleDB_button_iconwidget)
        self.article_authorDB_button_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.article_authorDB_button_iconwidget.setText("")
        self.article_authorDB_button_iconwidget.setIcon(icon4)
        self.article_authorDB_button_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.article_authorDB_button_iconwidget.setCheckable(True)
        self.article_authorDB_button_iconwidget.setAutoExclusive(True)
        self.article_authorDB_button_iconwidget.setObjectName("article_authorDB_button_iconwidget")
        self.article_authorDB_button_iconwidget.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_article_author, 'SELECT * FROM article_author'))
        self.verticalLayout.addWidget(self.article_authorDB_button_iconwidget)
        self.authorsDB_button_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.authorsDB_button_iconwidget.setText("")
        self.authorsDB_button_iconwidget.setIcon(icon4)
        self.authorsDB_button_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.authorsDB_button_iconwidget.setCheckable(True)
        self.authorsDB_button_iconwidget.setAutoExclusive(True)
        self.authorsDB_button_iconwidget.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_authors, 'SELECT * FROM authors'))
        self.authorsDB_button_iconwidget.setObjectName("authorsDB_button_iconwidget")
        self.verticalLayout.addWidget(self.authorsDB_button_iconwidget)
        self.authors_organisationsDB_button_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.authors_organisationsDB_button_iconwidget.setText("")
        self.authors_organisationsDB_button_iconwidget.setIcon(icon4)
        self.authors_organisationsDB_button_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.authors_organisationsDB_button_iconwidget.setCheckable(True)
        self.authors_organisationsDB_button_iconwidget.setAutoExclusive(True)
        self.authors_organisationsDB_button_iconwidget.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_authors_organisations, 'SELECT * FROM authors_organisations'))
        self.authors_organisationsDB_button_iconwidget.setObjectName("authors_organisationsDB_button_iconwidget")
        self.verticalLayout.addWidget(self.authors_organisationsDB_button_iconwidget)
        self.organisationsDB_button_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.organisationsDB_button_iconwidget.setText("")
        self.organisationsDB_button_iconwidget.setIcon(icon4)
        self.organisationsDB_button_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.organisationsDB_button_iconwidget.setCheckable(True)
        self.organisationsDB_button_iconwidget.setAutoExclusive(True)
        self.organisationsDB_button_iconwidget.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_organisations, 'SELECT * FROM organisations'))
        self.organisationsDB_button_iconwidget.setObjectName("organisationsDB_button_iconwidget")
        self.verticalLayout.addWidget(self.organisationsDB_button_iconwidget)
        self.addingdatatoBD_button_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.addingdatatoBD_button_iconwidget.setText("")
        self.addingdatatoBD_button_iconwidget.setIcon(icon4)
        self.addingdatatoBD_button_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.addingdatatoBD_button_iconwidget.setCheckable(False)
        self.addingdatatoBD_button_iconwidget.setAutoExclusive(True)
        self.addingdatatoBD_button_iconwidget.setObjectName("addingdatatoBD_button_iconwidget")
        self.verticalLayout.addWidget(self.addingdatatoBD_button_iconwidget)
        self.import_button_onlyiconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.import_button_onlyiconwidget.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/154837.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.import_button_onlyiconwidget.setIcon(icon5)
        self.import_button_onlyiconwidget.setIconSize(QtCore.QSize(20, 20))
        self.import_button_onlyiconwidget.setCheckable(True)
        self.import_button_onlyiconwidget.setAutoExclusive(True)
        self.import_button_onlyiconwidget.setObjectName("import_button_onlyiconwidget")
        self.verticalLayout.addWidget(self.import_button_onlyiconwidget)
        self.export_button_onlyiconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.export_button_onlyiconwidget.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/data-export-icon-0.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.export_button_onlyiconwidget.setIcon(icon6)
        self.export_button_onlyiconwidget.setIconSize(QtCore.QSize(20, 20))
        self.export_button_onlyiconwidget.setCheckable(True)
        self.export_button_onlyiconwidget.setAutoExclusive(True)
        self.export_button_onlyiconwidget.setObjectName("export_button_onlyiconwidget")
        self.verticalLayout.addWidget(self.export_button_onlyiconwidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.pushButton_5.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Sample_User_Icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon7)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 531, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.exit_iconwidget = QtWidgets.QPushButton(parent=self.widget_onlyicons)
        self.exit_iconwidget.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/x_close_cross_delete_icon_159748.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exit_iconwidget.setIcon(icon7)
        self.exit_iconwidget.setIconSize(QtCore.QSize(20, 20))
        self.exit_iconwidget.setCheckable(True)
        self.exit_iconwidget.setAutoExclusive(True)
        self.exit_iconwidget.setObjectName("exit_iconwidget")
        self.verticalLayout_3.addWidget(self.exit_iconwidget)
        self.gridLayout.addWidget(self.widget_onlyicons, 0, 0, 1, 1)
        self.widget_expanded = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_expanded.setMaximumSize(QtCore.QSize(147, 16777215))
        self.widget_expanded.setObjectName("widget_expanded")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_expanded)
        self.verticalLayout_4.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_expanded)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/ipng_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_expanded)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
                                   "    font-size: 14pt;\n"
                                   "    color: #eedd66;\n"
                                   "    font-weight: bold;\n"
                                   "    border-radius: 8px;\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.home_button_iconexpandedwidget = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.home_button_iconexpandedwidget.setIcon(icon3)
        self.home_button_iconexpandedwidget.setCheckable(True)
        self.home_button_iconexpandedwidget.setAutoExclusive(True)
        self.home_button_iconexpandedwidget.setObjectName("home_button_iconexpandedwidget")
        self.verticalLayout_2.addWidget(self.home_button_iconexpandedwidget)
        self.articleDB_button = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.articleDB_button.setIcon(icon4)
        self.articleDB_button.setCheckable(True)
        self.articleDB_button.setAutoExclusive(True)
        self.articleDB_button.setObjectName("articleDB_button")
        self.articleDB_button.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_article, 'SELECT * FROM article'))
        self.verticalLayout_2.addWidget(self.articleDB_button)
        self.article_authorDB_button = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.article_authorDB_button.setIcon(icon4)
        self.article_authorDB_button.setCheckable(True)
        self.article_authorDB_button.setAutoExclusive(True)
        self.article_authorDB_button.setObjectName("article_authorDB_button")
        self.article_authorDB_button.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_article_author, 'SELECT * FROM article_author'))
        self.verticalLayout_2.addWidget(self.article_authorDB_button)
        self.authorsDB_button = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.authorsDB_button.setIcon(icon4)
        self.authorsDB_button.setCheckable(True)
        self.authorsDB_button.setAutoExclusive(True)
        self.authorsDB_button.setObjectName("authorsDB_button")
        self.authorsDB_button.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_authors, 'SELECT * FROM authors'))
        self.verticalLayout_2.addWidget(self.authorsDB_button)
        self.authors_organisationsDB_button = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.authors_organisationsDB_button.setIcon(icon4)
        self.authors_organisationsDB_button.setCheckable(True)
        self.authors_organisationsDB_button.setAutoExclusive(True)
        self.authors_organisationsDB_button.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_authors_organisations, 'SELECT * FROM authors_organisations'))
        self.authors_organisationsDB_button.setObjectName("authors_organisationsDB_button")
        self.verticalLayout_2.addWidget(self.authors_organisationsDB_button)
        self.organisationsDB_button = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.organisationsDB_button.setIcon(icon4)
        self.organisationsDB_button.setCheckable(True)
        self.organisationsDB_button.setAutoExclusive(True)
        self.organisationsDB_button.setObjectName("organisationsDB_button")
        self.organisationsDB_button.clicked.connect(lambda: self.dataLoadFromDB(self.tableWidget_organisations, 'SELECT * FROM organisations'))
        self.verticalLayout_2.addWidget(self.organisationsDB_button)
        self.addingdatatoBD_button = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.addingdatatoBD_button.setIcon(icon4)
        self.addingdatatoBD_button.setCheckable(True)
        self.addingdatatoBD_button.setAutoExclusive(True)
        self.addingdatatoBD_button.setObjectName("addingdatatoBD_button")
        self.verticalLayout_2.addWidget(self.addingdatatoBD_button)
        self.import_button_expandedwidget = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.import_button_expandedwidget.setIcon(icon5)
        self.import_button_expandedwidget.setCheckable(True)
        self.import_button_expandedwidget.setAutoExclusive(True)
        self.import_button_expandedwidget.setObjectName("import_button_expandedwidget")
        self.verticalLayout_2.addWidget(self.import_button_expandedwidget)
        self.export_button_expandedwidget = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.export_button_expandedwidget.setIcon(icon6)
        self.export_button_expandedwidget.setCheckable(True)
        self.export_button_expandedwidget.setAutoExclusive(True)
        self.export_button_expandedwidget.setObjectName("export_button_expandedwidget")
        self.verticalLayout_2.addWidget(self.export_button_expandedwidget)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 547, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.exit_button_expandedwidget = QtWidgets.QPushButton(parent=self.widget_expanded)
        self.exit_button_expandedwidget.setIcon(icon7)
        self.exit_button_expandedwidget.setCheckable(True)
        self.exit_button_expandedwidget.setAutoExclusive(True)
        self.exit_button_expandedwidget.setObjectName("exit_button_expandedwidget")
        self.verticalLayout_4.addWidget(self.exit_button_expandedwidget)
        self.gridLayout.addWidget(self.widget_expanded, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.menu_button.toggled['bool'].connect(self.widget_onlyicons.setVisible) # type: ignore
        self.menu_button.toggled['bool'].connect(self.widget_expanded.setHidden) # type: ignore
        self.home_button_iconwidget.toggled['bool'].connect(self.home_button_iconexpandedwidget.setChecked) # type: ignore
        self.home_button_iconexpandedwidget.toggled['bool'].connect(self.home_button_iconwidget.setChecked) # type: ignore
        self.import_button_onlyiconwidget.toggled['bool'].connect(self.import_button_expandedwidget.setChecked) # type: ignore
        self.import_button_expandedwidget.toggled['bool'].connect(self.import_button_onlyiconwidget.setChecked) # type: ignore
        self.export_button_onlyiconwidget.toggled['bool'].connect(self.export_button_expandedwidget.setChecked) # type: ignore
        self.export_button_expandedwidget.toggled['bool'].connect(self.export_button_onlyiconwidget.setChecked) # type: ignore
        self.exit_button_expandedwidget.clicked.connect(MainWindow.close) # type: ignore
        self.exit_iconwidget.clicked.connect(MainWindow.close) # type: ignore
        self.articleDB_button_iconwidget.toggled['bool'].connect(self.articleDB_button.setChecked) # type: ignore
        self.articleDB_button.toggled['bool'].connect(self.articleDB_button_iconwidget.setChecked) # type: ignore
        self.article_authorDB_button_iconwidget.toggled['bool'].connect(self.article_authorDB_button.setChecked) # type: ignore
        self.article_authorDB_button.toggled['bool'].connect(self.article_authorDB_button_iconwidget.setChecked) # type: ignore
        self.authorsDB_button_iconwidget.toggled['bool'].connect(self.authorsDB_button.setChecked) # type: ignore
        self.authorsDB_button.toggled['bool'].connect(self.authorsDB_button_iconwidget.setChecked) # type: ignore
        self.authors_organisationsDB_button_iconwidget.toggled['bool'].connect(self.authors_organisationsDB_button.setChecked) # type: ignore
        self.authors_organisationsDB_button.toggled['bool'].connect(self.authors_organisationsDB_button_iconwidget.setChecked) # type: ignore
        self.organisationsDB_button_iconwidget.toggled['bool'].connect(self.organisationsDB_button.setChecked) # type: ignore
        self.organisationsDB_button.toggled['bool'].connect(self.organisationsDB_button_iconwidget.setChecked) # type: ignore
        self.addingdatatoBD_button_iconwidget.toggled['bool'].connect(self.addingdatatoBD_button.setChecked) # type: ignore
        self.addingdatatoBD_button.toggled['bool'].connect(self.addingdatatoBD_button_iconwidget.setChecked) # type: ignore
        self.pushButton_2.toggled['bool'].connect(self.pushButton_5.setChecked)  # type: ignore
        self.pushButton_5.toggled['bool'].connect(self.pushButton_2.setChecked)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Введите фамилию"))
        self.comboBox.setItemText(0, _translate("MainWindow", "2018"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2019"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2020"))
        self.comboBox.setItemText(3, _translate("MainWindow", "2021"))
        self.comboBox.setItemText(4, _translate("MainWindow", "2022"))
        self.comboBox.setItemText(5, _translate("MainWindow", "2023"))
        self.comboBox.setItemText(6, _translate("MainWindow", "2024"))
        self.comboBox.setItemText(7, _translate("MainWindow", "2025"))
        self.comboBox.setItemText(8, _translate("MainWindow", "2026"))
        self.comboBox.setItemText(9, _translate("MainWindow", "2027"))
        self.comboBox.setItemText(10, _translate("MainWindow", "2028"))
        self.Primary.setText(_translate("MainWindow", "Поиск"))
        self.add_one_row_button.setText(_translate("MainWindow", "Добавить строку в Базу Данных"))
        self.pushButton.setText(_translate("MainWindow", "Export to Excel"))
        self.general_data_export_button.setText(_translate("MainWindow", "Export to Excel"))
        self.label_3.setText(_translate("MainWindow", "  Database"))
        self.label_4.setText(_translate("MainWindow", "Импорт XML Файла "))
        self.home_button_iconexpandedwidget.setText(_translate("MainWindow", "Главная"))
        self.articleDB_button.setText(_translate("MainWindow", "Article"))
        self.article_authorDB_button.setText(_translate("MainWindow", "Article_author"))
        self.authorsDB_button.setText(_translate("MainWindow", "Authors"))
        self.authors_organisationsDB_button.setText(_translate("MainWindow", "Authors_organisations"))
        self.organisationsDB_button.setText(_translate("MainWindow", "Organisations"))
        self.addingdatatoBD_button.setText(_translate("MainWindow", "Добавление данных"))
        self.import_button_expandedwidget.setText(_translate("MainWindow", "Импорт"))
        self.export_button_expandedwidget.setText(_translate("MainWindow", "Экспорт"))
        self.pushButton_2.setText(_translate("MainWindow", "Общий экспорт"))
        self.exit_button_expandedwidget.setText(_translate("MainWindow", "Выход"))

    def dataLoadFromDB(self,tableWidget, query):
            conn = psycopg2.connect(database=database_parametres['dbname'],
                                    user=database_parametres['user'],
                                    password=database_parametres['password'],
                                    host=database_parametres['host'],
                                    port=database_parametres['port'])
            cur = conn.cursor()
            cur.execute(query)
            result = cur.fetchall()
            tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
            cur.close()
            conn.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
